### ISSUE TITLE
dosvpn readme assets

### ISSUE THREAD

**Issue by dodois** [dodois/dosvpn#1]
![logo-256](https://user-images.githubusercontent.com/73285310/97069620-0edd5a80-1604-11eb-965f-79582462d6e5.png)

**Comment by dodois** [comment]
![Snipaste_2020-10-24_14-58-51](https://user-images.githubusercontent.com/73285310/97070335-1acc1b00-160a-11eb-8e18-e9d9d3850a6e.png)

**Comment by dodois** [comment]
![Snipaste_2020-10-24_15-04-42](https://user-images.githubusercontent.com/73285310/97070362-46e79c00-160a-11eb-91e6-9633e78fd311.png)

**Comment by dodois** [comment]
![Uploading Video_2020-10-24_200344.wmv_20201024_200446.gif…]()

**Comment by dodois** [comment]
![Video_2020-10-24_200344 wmv_20201024_200446](https://user-images.githubusercontent.com/73285310/97081336-61cf0600-1634-11eb-9f58-d80098d84b5e.gif)

**Comment by dodois** [comment]
![5f9419bdc46e3_5f9419be6d5eb](https://user-images.githubusercontent.com/73285310/97081474-3dbff480-1635-11eb-867c-c89a49c30fdc.gif)

**Comment by dodois** [comment]
![0c35cea2b8664c869a2eeb9544de53e1](https://user-images.githubusercontent.com/73285310/98082800-4aa1db00-1eb4-11eb-8183-d39866fc5880.jpeg)

**Comment by dodois** [comment]
![Snipaste_2020-11-08_15-37-34](https://user-images.githubusercontent.com/73285310/98459725-65d45980-21d8-11eb-88f7-6c70a0755cae.png)

**Comment by adejuc** [comment]
![Uploading image.png…]()

**Comment by adejuc** [comment]
![image](https://user-images.githubusercontent.com/75061362/102582933-9cd64d00-413e-11eb-9c25-52ed05379bfd.png)

**Comment by adejuc** [comment]
![image](https://user-images.githubusercontent.com/75061362/102582952-a8c20f00-413e-11eb-8af0-55962f00163b.png)

**Comment by adejuc** [comment]
![image](https://user-images.githubusercontent.com/75061362/102583055-dc9d3480-413e-11eb-8ce8-231fa560b957.png)

**Comment by adejuc** [comment]
![image](https://user-images.githubusercontent.com/75061362/102583078-e888f680-413e-11eb-9e85-6784c28c118a.png)

**Comment by adejuc** [comment]
![image](https://user-images.githubusercontent.com/75061362/102741397-3004c200-438d-11eb-9d1b-a5edd116d6e4.png)
![image](https://user-images.githubusercontent.com/75061362/102741405-32ffb280-438d-11eb-8dd8-e13b41277a40.png)
![image](https://user-images.githubusercontent.com/75061362/102741415-3abf5700-438d-11eb-868b-b7427c25d962.png)
![image](https://user-images.githubusercontent.com/75061362/102741421-3f840b00-438d-11eb-96a3-da912f2fc9b8.png)
![image](https://user-images.githubusercontent.com/75061362/102741432-43b02880-438d-11eb-8fee-b6a90d007f03.png)

**Comment by adejuc** [comment]
![image](https://user-images.githubusercontent.com/75061362/102741493-7528f400-438d-11eb-944c-9d93318374ab.png)
![image](https://user-images.githubusercontent.com/75061362/102741496-76f2b780-438d-11eb-95d1-6009edb7baaa.png)
![image](https://user-images.githubusercontent.com/75061362/102741502-79551180-438d-11eb-8135-e402de2cd165.png)
