### ISSUE TITLE
晚上的速度实在太慢了，不能再优化了吗？youtube速度只有几十K

### ISSUE THREAD

**Issue by yDan** [dodois/dosvpn#11]
晚上的速度实在太慢了，不能再优化了吗？youtube速度只有几十K

**Comment by dodois** [comment]
我们已经很努力了，请给我们足够的时间，耐心期待Dosvpn的每一次升级

**Comment by Rqcker** [comment]
项目还是在不断的改善，非常理解。现在彻底免费的开源的梯子真的很少，在此相信可以一直贯彻免费开源的传统！
