### ISSUE TITLE
昨天速度非常快，今天又不行了。全部节点都被封了？

### ISSUE THREAD

**Issue by yDan** [dodois/dosvpn#12]
昨天速度非常快，今天又不行了。全部节点都被封了？

**Comment by dodois** [comment]
可尝试使用 “未知20”、“未知21”等应急
如果无法获取节点，可通过以下两种方式（任选其一）手动配置：
1. 更改hosts文件 199.232.68.133 raw.githubusercontent.com
2. 将[此处](https://github.com/dodois/dosvpn-config/tree/main/outputs)的config文件,下载并重命名为net，放到```C:\Program Files\dodois\dosvpn\Dos Vpn\resources``` 目录中，然后将除config外的所有文件下载，存放到```C:\Program Files\dodois\dosvpn\Dos Vpn\resources\config``` 中
