### ISSUE TITLE
大批节点已无法使用，我们将在今天下午3点，更新一批新的节点

### ISSUE THREAD

**Issue by dodois** [dodois/dosvpn#13]
节点已更新，目前只能手动一个一个测试节点的可用性，测试时请耐心等待8-10秒，延迟稳定后才能确定节点的可用性，刚连接时延迟普遍偏高属于正常现象。目前上新的节点请自行手动测试可用性，我们将在1.1.1版本推出节点自动优选功能。

### 香港3 节点，youtube高清无缓冲！

~~大家可尝试使用 “未知20”、“未知21”等应急。如果各位有发现新的可用的节点，请到此处留言以方便别的同学。
3点后请大家手动点击刷新按钮获取新的节点。~~
如果无法获取节点，可通过以下两种方式（任选其一）手动配置：
1. 更改hosts文件 199.232.68.133 raw.githubusercontent.com
2. 将[此处](https://github.com/dodois/dosvpn-config/tree/main/outputs)的config文件,下载并重命名为net，放到```C:\Program Files\dodois\dosvpn\Dos Vpn\resources``` 目录中，然后将除config外的所有文件下载，存放到```C:\Program Files\dodois\dosvpn\Dos Vpn\resources\config``` 中

**Comment by yDan** [comment]
为什么那么容易被封的？昨天的速度非常非常快，看youtube压根都不用缓冲。打开任何外网都非常非常快。为什么那么容易被封的？

**Comment by dodois** [comment]
节点已更新，目前只能手动一个一个测试节点的可用性，测试时请耐心等待8-10秒，延迟稳定后才能确定节点的可用性，刚连接时延迟普遍偏高属于正常现象。目前上新的节点请自行手动测试可用性，我们将在1.1.1版本推出节点自动优选功能

**Comment by yDan** [comment]
> 节点已更新，目前只能手动一个一个测试节点的可用性，测试时请耐心等待8-10秒，延迟稳定后才能确定节点的可用性，刚连接时延迟普遍偏高属于正常现象。目前上新的节点请自行手动测试可用性，我们将在1.1.1版本推出节点自动优选功能

还是不行，没有一个节点能用的。

**Comment by tempaccount-1** [comment]
> > 节点已更新，目前只能手动一个一个测试节点的可用性，测试时请耐心等待8-10秒，延迟稳定后才能确定节点的可用性，刚连接时延迟普遍偏高属于正常现象。目前上新的节点请自行手动测试可用性，我们将在1.1.1版本推出节点自动优选功能
> 
> 还是不行，没有一个节点能用的。
我这刷新了之后就有能用的节点了
![A62BBF7B-5766-4a5a-9CCB-D3AA1AEAD7B2](https://user-images.githubusercontent.com/73453932/98212385-79848380-1f7e-11eb-9073-b07f4e00f8d0.png)

**Comment by yDan** [comment]
> > > 节点已更新，目前只能手动一个一个测试节点的可用性，测试时请耐心等待8-10秒，延迟稳定后才能确定节点的可用性，刚连接时延迟普遍偏高属于正常现象。目前上新的节点请自行手动测试可用性，我们将在1.1.1版本推出节点自动优选功能
> > 
> > 
> > 还是不行，没有一个节点能用的。
> > 我这刷新了之后就有能用的节点了
> > ![A62BBF7B-5766-4a5a-9CCB-D3AA1AEAD7B2](https://user-images.githubusercontent.com/73453932/98212385-79848380-1f7e-11eb-9073-b07f4e00f8d0.png)

我这里刷新之后都没有看到有韩国，香港3的节点。刷新跟没刷新都是一样的节点。不知道哪里出问题？

**Comment by tempaccount-1** [comment]
> > > > 节点已更新，目前只能手动一个一个测试节点的可用性，测试时请耐心等待8-10秒，延迟稳定后才能确定节点的可用性，刚连接时延迟普遍偏高属于正常现象。目前上新的节点请自行手动测试可用性，我们将在1.1.1版本推出节点自动优选功能
> > > 
> > > 
> > > 还是不行，没有一个节点能用的。
> > > 我这刷新了之后就有能用的节点了
> > > ![A62BBF7B-5766-4a5a-9CCB-D3AA1AEAD7B2](https://user-images.githubusercontent.com/73453932/98212385-79848380-1f7e-11eb-9073-b07f4e00f8d0.png)
> 
> 我这里刷新之后都没有看到有韩国，香港3的节点。刷新跟没刷新都是一样的节点。不知道哪里出问题？

我一开始也不行，然后跟着1楼的建议1手动配置了一下hosts文件，之后刷新就成功了

**Comment by yDan** [comment]
> > > > > 节点已更新，目前只能手动一个一个测试节点的可用性，测试时请耐心等待8-10秒，延迟稳定后才能确定节点的可用性，刚连接时延迟普遍偏高属于正常现象。目前上新的节点请自行手动测试可用性，我们将在1.1.1版本推出节点自动优选功能
> > > > 
> > > > 
> > > > 还是不行，没有一个节点能用的。
> > > > 我这刷新了之后就有能用的节点了
> > > > ![A62BBF7B-5766-4a5a-9CCB-D3AA1AEAD7B2](https://user-images.githubusercontent.com/73453932/98212385-79848380-1f7e-11eb-9073-b07f4e00f8d0.png)
> > 
> > 
> > 我这里刷新之后都没有看到有韩国，香港3的节点。刷新跟没刷新都是一样的节点。不知道哪里出问题？
> 
> 我一开始也不行，然后跟着1楼的建议1手动配置了一下hosts文件，之后刷新就成功了

那个hosts文件怎么配置啊，能发个图吗？我不懂啊，我是小白。

**Comment by yDan** [comment]
我的honst文件是这样的

**Comment by yDan** [comment]
我的honst文件是这样的
![Uploading image.png…]()

**Comment by liDonginter** [comment]
好了

**Comment by yDan** [comment]
确实改了一下hosts可以更新节点了。但不知道明天会不会又封了。

**Comment by yDan** [comment]
香港3也挂了。

**Comment by yDan** [comment]
怎么挂得那么快

**Comment by dodois** [comment]
用 香港2
