### ISSUE TITLE
关于虚拟机中使用的问题

### ISSUE THREAD

**Issue by fentuoli** [dodois/dosvpn#16]
你好，请问这个可以在虚拟机中的linux环境下使用吗？非常感谢！

**Comment by Rqcker** [comment]
Linux/Unix 目前都不可以 现在只支持Windows平台

**Comment by dodois** [comment]
@fentuoli 暂不支持linux，但是linux在我们的开发计划中

**Comment by fentuoli** [comment]
请问随后有可能提供linux平台的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dodois/dosvpn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 晚上10:12
收件人:&nbsp;"dodois/dosvpn"<dosvpn@noreply.github.com&gt;;
抄送:&nbsp;"般若"<1109956207@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dodois/dosvpn] 关于虚拟机中使用的问题 (#16)





 
Linux/Unix 目前都不可以 现在只支持Windows平台

**Comment by fentuoli** [comment]
好的，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dodois/dosvpn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 晚上10:12
收件人:&nbsp;"dodois/dosvpn"<dosvpn@noreply.github.com&gt;;
抄送:&nbsp;"般若"<1109956207@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dodois/dosvpn] 关于虚拟机中使用的问题 (#16)





 
@fentuoli 暂不支持linux，但是linux在我们的开发计划中

**Comment by dodois** [comment]
今天才刚是项目上线的第13天，所以请静静等待，持续关注Dodois，谢谢

**Comment by fentuoli** [comment]
好的，非常期待！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dodois/dosvpn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 晚上10:14
收件人:&nbsp;"dodois/dosvpn"<dosvpn@noreply.github.com&gt;;
抄送:&nbsp;"般若"<1109956207@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dodois/dosvpn] 关于虚拟机中使用的问题 (#16)





 
今天才刚是项目上线的第13天，所以请静静等待，持续关注Dodois，谢谢
