### ISSUE TITLE
关于刷新节点没有变化的问题

### ISSUE THREAD

**Issue by Rqcker** [dodois/dosvpn#17]
尝试刷新节点 但是没有变化 依旧是原来的默认节点
部分节点切换失败 少数默认节点可以成功切换

**Comment by dodois** [comment]
# 由于运营商问题，导致Dosvpn无法连接GitHub服务的处理办法（刷新配置，切换节点等基于github服务）

### 1. 手动修改配置

a. 将 [dos-config](https://github.com/dodois/dosvpn-config/blob/main/outputs/config) 仓库下载下来

b. 将 `outputs/config` 文件重命名为 net，放到`C:\Program Files\dodois\dosvpn\Dos Vpn\resources` 目录中

c. 将 `outputs` 文件夹中的其他文件存放到`C:\Program Files\dodois\dosvpn\Dos Vpn\resources\config` 中

d. 重新启动应用

### 2. 手动修改 HOSTS 文件

a. 进入 `C:\Windows\System32\drivers\etc` 文件夹

b. 找到 `hosts` 文件，没有就创建一个，复制到桌面

c. 用记事本打开，在新的一行中粘贴 `199.232.68.133 raw.githubusercontent.com`

d. 保存

e. 将修改后的 hosts 文件拖回 `C:\Windows\System32\drivers\etc` 文件夹中替换原始 hosts

f. 刷新节点

**Comment by dodois** [comment]
@Rqcker Dosvpn 节点配置会在每天上午10-12点更新，后面会根据具体情况调整更新时机，如无法更新，请参考以上解决办法
