### ISSUE TITLE
关于节点获取失败

### ISSUE THREAD

**Issue by fentuoli** [dodois/dosvpn#20]
网络连接正常且配置过hosts文件后，手动切换每个节点都提示节点获取失败，是什么原因呢？

**Comment by dodois** [comment]
@fentuoli 关闭Dosvpn及其他代理软件，尝试是否能打开如下地址```https://raw.githubusercontent.com/dodois/dosvpn-config/main/outputs/config```，如果页面显示全屏乱码代表能打开，否则不能打开，不能打开的情况请尝试修改DNS为```8.8.8.8```，```8.8.4.4```。如果可以打开，请并尝试删除```C:\Program Files\dodois\dosvpn\Dos Vpn\resources```中的```net```文件，与```config```文件夹中所有文件，再次打开Dosvpn，点击刷新。

**Comment by dodois** [comment]
如果以上操作无法依然无法正常刷新节点，请尝试手动修改配置
a. 将 dos-config 仓库下载下来

b. 将 outputs/config 文件重命名为 net，放到C:\Program Files\dodois\dosvpn\Dos Vpn\resources 目录中

c. 将 outputs 文件夹中的其他文件存放到C:\Program Files\dodois\dosvpn\Dos Vpn\resources\config 中

d. 重新启动应用

**Comment by fentuoli** [comment]
我前面配置过该文件夹，但刚才打开发现config中的文件只剩4个，不知道为什么其余文件消失了。我重新配置后可以正常切换节点！感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dodois/dosvpn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月6日(星期五) 晚上8:44
收件人:&nbsp;"dodois/dosvpn"<dosvpn@noreply.github.com&gt;;
抄送:&nbsp;"般若"<1109956207@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dodois/dosvpn] 关于节点获取失败 (#20)





 
@fentuoli 关闭Dosvpn及其他代理软件，尝试是否能打开如下地址https://raw.githubusercontent.com/dodois/dosvpn-config/main/outputs/config，如果页面显示全屏乱码代表能打开，否则不能打开，不能打开的情况请尝试修改DNS为8.8.8.8，8.8.4.4。如果可以打开，请并尝试删除C:\Program Files\dodois\dosvpn\Dos Vpn\resources中的net文件，与config文件夹中所有文件，再次打开Dosvpn，点击刷新。

**Comment by fentuoli** [comment]
我重新配置过该文件夹后可以正常切换节点，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dodois/dosvpn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月6日(星期五) 晚上8:45
收件人:&nbsp;"dodois/dosvpn"<dosvpn@noreply.github.com&gt;;
抄送:&nbsp;"般若"<1109956207@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dodois/dosvpn] 关于节点获取失败 (#20)





 
如果以上操作无法依然无法正常刷新节点，请尝试手动修改配置
 a. 将 dos-config 仓库下载下来
 
b. 将 outputs/config 文件重命名为 net，放到C:\Program Files\dodois\dosvpn\Dos Vpn\resources 目录中
 
c. 将 outputs 文件夹中的其他文件存放到C:\Program Files\dodois\dosvpn\Dos Vpn\resources\config 中
 
d. 重新启动应用

**Comment by dodois** [comment]
@fentuoli 每一次刷新会清除缓存的节点文件，清除后由于某些原因导致无法再次成功下载，所以config中文件数量仅有之前下载成功的那几个
