### ISSUE TITLE
节点刚刚连接上时的延迟不具备参考性

### ISSUE THREAD

**Issue by dodois** [dodois/dosvpn#21]
## 连接成功后1秒
![Snipaste_2020-11-07_22-58-59](https://user-images.githubusercontent.com/73285310/98444507-0ed57280-214d-11eb-9c34-d62086e5f787.png)
## 连接成功后10秒
![Snipaste_2020-11-07_22-58-35](https://user-images.githubusercontent.com/73285310/98444513-15fc8080-214d-11eb-950d-fae9088c45de.png)

**Comment by yDan** [comment]
虽然连接上，但是打开网页速度和youtube很慢，YouTube缓冲要缓冲很久才能播放。

**Comment by dodois** [comment]
@yDan 可以多次切换节点尝试
