### ISSUE TITLE
releases下载不动，能不能把安装文件同步到仓库里，这样通过gitee克隆后下载就很快了

### ISSUE THREAD

**Issue by HelloDB** [dodois/dosvpn#22]

**Comment by dodois** [comment]
@HelloDB 下载慢或下载失败，可以选择使用[Motrix](https://motrix.app/)，一款开源的下载工具

**Comment by HelloDB** [comment]
谢谢回复，使用Motrix也下载不动，github慢点倒是下载完成了，安装试了一下自动手动都连不上，有没有类似蓝灯的梯子推荐，蓝灯现在基本废了。稳定好用的收费一千以内能接受
