### ISSUE TITLE
刷新节点，一直在转圈圈，没完没了。

### ISSUE THREAD

**Issue by yDan** [dodois/dosvpn#26]
![QQ图片20201111132514](https://user-images.githubusercontent.com/21190788/98772468-b094e200-2421-11eb-86db-43fd1f1efd59.png)

**Comment by dodois** [comment]
@yDan 此问题已知悉，该版为实验版，目前正在着手修复实验版中所有已知异常

**Comment by dodois** [comment]
@yDan  1.1.2 正式版已上线，[传送门](https://github.com/dodois/dosvpn/releases/download/v1.1.2/Dos-VPN-Setup-1.1.2.exe)
