### ISSUE TITLE
win10安装不上

### ISSUE THREAD

**Issue by jiaobendaye** [dodois/dosvpn#31]
安装到一半显示安装中止

**Comment by dodois** [comment]
@jiaobendaye 请上传两张安装时的截图

**Comment by jiaobendaye** [comment]
![image](https://user-images.githubusercontent.com/32284532/99329892-2255ab80-28ba-11eb-8398-4b3997474e35.png)

应该是我电脑的问题，公司的电脑，有很多限制。我换我自己的就可以了

**Comment by yuliangl** [comment]
> @jiaobendaye 请上传两张安装时的截图

我确实和他遇到的一样，我关了windows defender， qq电脑管家，全部删除再从新下载还是没有效果！
