### ISSUE TITLE
开发中的项目会有大量的问题存在，请大家及时向我们反馈

### ISSUE THREAD

**Issue by dodois** [dodois/dosvpn#4]

**Comment by UTSOURCE** [comment]
okokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokok......

**Comment by hsj1997** [comment]
怎么运行啊

**Comment by dodois** [comment]
@hsj1997 [点击此处下载 1.0.8](https://github.com/dodois/dosvpn/releases/download/v1.0.8/Dos-VPN-Setup-1.0.8.exe)

**Comment by allentown521** [comment]
wonderful job

**Comment by yuliangl** [comment]
是不是特别慢啊？ gmail都打不开呢？

**Comment by dodois** [comment]
@yuliangl 1.1.2 正式版已上线，[传送门](https://github.com/dodois/dosvpn/releases/download/v1.1.2/Dos-VPN-Setup-1.1.2.exe)

**Comment by yuliangl** [comment]
> @yuliangl 1.1.2 正式版已上线，[传送门](https://github.com/dodois/dosvpn/releases/download/v1.1.2/Dos-VPN-Setup-1.1.2.exe)

一点击安装就显示 安装已终止，无法成功安装！！！.......

**Comment by dodois** [comment]
@yuliangl 你可能遇到的情况与这里一样 https://github.com/dodois/dosvpn/issues/31 ，如果需要我们的帮助，请尽量提供一些相关的参数给我们，比如系统信息等

**Comment by bugfix2020** [comment]
获取节点信息失败

**Comment by dodois** [comment]
@bugfix2020 获取节点信息失败，请参考如下解决方案
### 常见问题解答 Q&A
1. 提示“获取节点配置失败”或“节点获取失败”

   > 刷新节点时，提示以上错误，表示你的运营商已阻止你访问如下网址[https://raw.githubusercontent.com/dodois/dosvpn-config/main/outputs/config](https://raw.githubusercontent.com/dodois/dosvpn-config/main/outputs/config)
   >
   > - 如果浏览器出现满屏乱码，表示可以正常访问，此时请通过[手动配置方法](https://github.com/dodois/dosvpn/blob/main/manual.md)进行处理，
   > - 如果页面打不开，你仅需要配置```hosts```文件，点此查看[hosts 配置方法](https://github.com/dodois/dosvpn/blob/main/hosts.md)

2. 修改 hosts 不生效处理办法
   > 点此查看[手动配置方法](https://github.com/dodois/dosvpn/blob/main/manual.md)

**Comment by dodois** [comment]
如果配置了hosts文件仍然获取失败，请尝试更改dns.
根据不同的网络环境dns可能不经相同，以下给出我自己在用的dns以供参考
![image](https://user-images.githubusercontent.com/73285310/99984505-18ff9e00-2de8-11eb-9ffa-3d2d30a6b273.png)

**Comment by dingsahnghuafo** [comment]
感觉最新版的1.14好像连不上网了

**Comment by dodois** [comment]
@dingsahnghuafo 最新版为 1.1.3 , 此版本某些情况下可能与之前版本不兼容，请先卸载之前版本

**Comment by Zheng-Luxi** [comment]
Windows 7 32 位系统用不了吗？
