### ISSUE TITLE
使用不了谷歌学术

### ISSUE THREAD

**Issue by Young236** [dodois/dosvpn#41]
请问一下，用这个为什么使用不了谷歌学术

**Comment by dodois** [comment]
请尝试切换节点，如果切换节点依然无效，请尝试切换全局/智能模式，如果以上方式依然无效，请向我们汇报此问题，如果生效，请问我们反馈，谢谢

**Comment by Young236** [comment]
切换节点和切换全局/智能模式都试了，好像都不行

**Comment by adejuc** [comment]
换节点应该可以的吧，我换节点登录谷歌学术是没有问题的呀
