### ISSUE TITLE
[Other]没办法用啊

### ISSUE THREAD

**Issue by wzzzzx** [dodois/dosvpn#45]
![image](https://user-images.githubusercontent.com/64118119/101984490-b69a0f00-3cbc-11eb-9eb6-d4da34d204b9.png)
显示是这个 但是推特和油管都上不去
用的是Google浏览器

**Comment by wzzzzx** [comment]
我发现edge浏览器可以上油管
但是Google浏览器不行
这是为什么？

**Comment by dodois** [comment]
请排查是否由于chrome浏览器代理插件造成

**Comment by wzzzzx** [comment]
> 请排查是否由于chrome浏览器代理插件造成

请问怎么看自己是否安装了代理插件呢

**Comment by dodois** [comment]
@wzzzzx 请把chrome浏览器 已安装的扩展插件界面的截图贴上来
