### ISSUE TITLE
移动用户无法使用Dosvpn

### ISSUE THREAD

**Issue by dodois** [dodois/dosvpn#48]
目前已知移动网络大概率会无法更新节点及正常使用Dosvpn，请了解相关知识或遇到同样问题的同学在此进行回复，以便我们尽快给出解决方案

**Comment by ZK6100HGA** [comment]
可以尝试把节点文件放在别的地方，例如cloudflare worker、heroku、now.sh、jsdelivr、gitlab和amazon s3等。

**Comment by dodois** [comment]
@ZK6100HGA 不错的建议^_^
