### ISSUE TITLE
获取配置文件失败 切无法连接

### ISSUE THREAD

**Issue by bugfix2020** [dodois/dosvpn#49]
1、已经检查HOST
2、https://raw.githubusercontent.com/dodois/dosvpn-config/main/outputs/config 能打开
3、网络为联通
![image](https://user-images.githubusercontent.com/29813979/102897297-bfe86000-44a2-11eb-8950-92da35a4cafe.png)

![image](https://user-images.githubusercontent.com/29813979/102897648-53219580-44a3-11eb-8cb0-6d92d9710377.png)

**Comment by dodois** [comment]
@bugfix2020 之前版本是否使用正常呢？如果之前版本使用正常，请卸载当前版本，再次重新安装

**Comment by dodois** [comment]
@bugfix2020 重新安装后如果依然无法连接，请及时向我们上报异常，谢谢

**Comment by dodois** [comment]
@bugfix2020 是否有尝试更换DNS，当然此回复我无法确认是否有效，[一款优秀的DNS更换器](https://www.sordum.org/downloads/?dns-jumper)

**Comment by bugfix2020** [comment]
> @ bugfix2020是否有尝试更换DNS，当然此回复我无法确认是否有效，[某些优秀的DNS更换器](https://www.sordum.org/downloads/?dns-jumper)

1、dns使用过8.8.8.8和114.114.114

**Comment by bugfix2020** [comment]
是否需要上报异常log文件以供排查？

**Comment by dodois** [comment]
@bugfix2020 
图中报错是由于，配置文件获取失败，[下载net](https://raw.githubusercontent.com/dodois/dosvpn-config/main/outputs/config)，成功下载该文件后，将此文件重命名为net并存放到resource目录中，重启软件后将获得最新节点，此时无需再次刷新节点，仅需进行节点测速，即可使用

**Comment by dodois** [comment]
> @bugfix2020
> 请完全卸载当前版本，再次重新安装到新的目录。
> 
> > 我们已收到该问题的多次反馈，解决办法均为以上操作.
> 
> 关于你发布图中的报错是由于，配置文件获取失败，成功下载[该文件](https://raw.githubusercontent.com/dodois/dosvpn-config/main/outputs/config)后，将此文件重命名为net并存放到resource目录中，重启软件后将获得最新节点，此时无需再次刷新节点，仅需进行节点测速

**Comment by bugfix2020** [comment]
> @bugfix2020
> 关于1.1.2 升级到1.1.3 所有节点均无法使用的解决方法：请完全卸载当前版本，再次重新安装到新的目录。
> 
> > 我们已收到该类似问题的多次反馈，解决办法均为以上操作.
> 
> 关于你发布图中的报错是由于，配置文件获取失败，成功下载[该文件](https://raw.githubusercontent.com/dodois/dosvpn-config/main/outputs/config)后，将此文件重命名为net并存放到resource目录中，重启软件后将获得最新节点，此时无需再次刷新节点，仅需进行节点测速

好的 按照步骤执行 目前已恢复 谢谢！

**Comment by dodois** [comment]
@bugfix2020 感谢反馈，现在关闭问题

**Comment by bugfix2020** [comment]
> @bugfix2020 感谢反馈，现在关闭问题

问题复现
更新节点后测速ok
但是连接后就会出现“网络异常错误"
