### ISSUE TITLE
wifi热点无法科学上网

### ISSUE THREAD

**Issue by Muskchen** [dodois/dosvpn#50]
电脑科学上网没有问题，但是分享的wifi热点不能科学上网

**Comment by dodois** [comment]
@Muskchen 
### 手机连接电脑VPN的解决办法
Dos VPN手机版app目前正在开发中，在app上线之前您如果想使用手机连接VPN，可以使用电脑端工具中心的手机上网功能。 
1. 使用该功能需要先在设置中心开启允许局域网连接，然后重新连接VPN
2. 进入手机上网工具，点击开启热点后，手机扫码或是手动输入WiFi名称和密码连接电脑的热点，注意必须电脑网卡支持热点开启功能才可以使用。 

## 注意：手机连接热点后，还需要在手机上设置代理。具体操作为设置→WLAN→显示高级选项→代理服务器→手动，然后填写IP和端口

![image](https://user-images.githubusercontent.com/73285310/103013869-cfd27380-4578-11eb-9948-e1e34c0226d6.png)
![image](https://user-images.githubusercontent.com/73285310/103013888-d95bdb80-4578-11eb-91db-d5a6ae9095b6.png)

**Comment by dodois** [comment]
### 查看本机IP地址的方法： 
方法一：鼠标右键单击【开始】，选择【网络链接】-【以太网】-【网络和共享中心】-【网络连接】-【详细信息】即可查看IP；
![image](https://user-images.githubusercontent.com/73285310/103013949-f5f81380-4578-11eb-953b-1520473bdd52.png)

方法二：电脑快捷键【win+R】打开运行窗口输入【cmd】，点击【确定】，在弹出的窗口代码末尾输入【ipconfig】，【回车】即可。
![image](https://user-images.githubusercontent.com/73285310/103014023-132ce200-4579-11eb-8d35-915b111c0e50.png)

**Comment by Muskchen** [comment]
代理端口是多少？在哪查看？

**Comment by dodois** [comment]
@Muskchen 代理端口默认为1080

**Comment by Rqcker** [comment]
遇到的问题：
添加代理服务器前无法访问外网
添加代理服务器后手机显示没有网络，内网和外网都访问不了
