### ISSUE TITLE
🚩 下个版本你希望看到的小工具

### ISSUE THREAD

**Issue by dodois** [dodois/dosvpn#51]
告诉我们你希望加入Dosvpn的实用小工具

Dodois 正在考虑加入：
1. 下载工具，以替代传统迅雷
2. 网络修复工具，一键解决上网问题
3. 广告拦截
4. 局域网文件传输
5. 自定义节点（订阅或自定义）
6. ....

**Comment by ZK6100HGA** [comment]
全局代理模式，用来针对那些没法走系统代理的软件。

**Comment by dodois** [comment]
@ZK6100HGA 嗯，已采纳
