### ISSUE TITLE
[BUG]手动下载更新了节点，也用不了

### ISSUE THREAD

**Issue by allentown521** [dodois/dosvpn#52]
# Bug Report

**DosVpn 版本:**
1.1.3

**Bug 描述:**
之前都可以正常使用的，现在手动下载更新了节点，也用不了

**你所认为正常的情况:**

**其他信息:**

**Comment by dodois** [comment]
请查看此贴是否有帮助 
https://github.com/dodois/dosvpn/issues/49#issuecomment-750005469

**Comment by allentown521** [comment]
[image: image.png]
节点刷新成功，也显示连接成功，但是每次测速时就说异常

dodois <notifications@github.com> 于2020年12月24日周四 下午5:25写道：

**Comment by dodois** [comment]
@allentown521 无法查看图片，请重新上传以便于Dodois排查问题

**Comment by bugfix2020** [comment]
> @allentown521 无法查看图片，请重新上传以便于Dodois排查问题

我的问题复现了
测速ok
但是连接就出现“网络连接异常”的提示
![image](https://user-images.githubusercontent.com/29813979/103095765-c14d9000-463c-11eb-945f-e21bdb3c56d5.png)

**Comment by dodois** [comment]
目前尚不可知该问题出现的原因，但已多次出现。Dodois 正在全力排查，请尝试杀死进程重启软件。

**Comment by dodois** [comment]
目前观察到，该问题可能与 设置中心 - 启动后自动连接(开启) 有关。请在新版本到来前暂时关闭该选项，并重启Dosvpn

**Comment by ZK6100HGA** [comment]
> 
> 
> 目前观察到，该问题可能与 设置中心 - 启动后自动连接(开启) 有关。请在新版本到来前暂时关闭该选项，并重启Dosvpn
还是不行啊。

**Comment by ZK6100HGA** [comment]
> 
> 
> 目前观察到，该问题可能与 设置中心 - 启动后自动连接(开启) 有关。请在新版本到来前暂时关闭该选项，并重启Dosvpn

还是不行啊。

**Comment by dodois** [comment]
@ZK6100HGA 能放上截图并大致描述下情况吗？

**Comment by ZK6100HGA** [comment]
> 
> 
> @ZK6100HGA 能放上截图并大致描述下情况吗？

跟楼上一样。
