### ISSUE TITLE
【紧急】已知可能导致无法使用的bug

### ISSUE THREAD

**Issue by dodois** [dodois/dosvpn#53]
问题描述: 测速正常，切换节点时，节点下方提示网络异常
可能的解决办法：完全卸载，并在新位置重装软件
问题分析：目前尚不可知该问题的诱发原因，Dodois正在全力排查

**Comment by dodois** [comment]
目前观察到，该问题可能与 设置中心 - 启动后自动连接(开启) 有关。请在新版本到来前暂时关闭该选项，并重启Dosvpn

**Comment by Yoka416** [comment]
还是不行

**Comment by dodois** [comment]
@Yoka416 请回退到 [1.1.2 稳定版](https://github.com/dodois/dosvpn/releases/download/v1.1.2/Dos-VPN-Setup-1.1.2.exe)，感谢您的支持

**Comment by Yoka416** [comment]
> @Yoka416 请回退到 [1.1.2 稳定版](https://github.com/dodois/dosvpn/releases/download/v1.1.2/Dos-VPN-Setup-1.1.2.exe)，感谢您的支持

哦哦好的，1，1.2版本在哪里下载

**Comment by dodois** [comment]
点击 蓝色连接 即可下载

**Comment by Yoka416** [comment]
> 点击 蓝色连接 即可下载

哦哦好的，谢谢！

**Comment by Yoka416** [comment]
> 点击 蓝色连接 即可下载

大佬，稳定版不能下载，下载一半总是提示服务器拒绝请求。我试了几个下载软件都不行。

**Comment by Yoka416** [comment]
> 点击 蓝色连接 即可下载

可以了，谢谢！！

**Comment by bugfix2020** [comment]
> 目前观察到，该问题可能与 设置中心 - 启动后自动连接(开启) 有关。请在新版本到来前暂时关闭该选项，并重启Dosvpn

按照此方法 目前连接已恢复 赞
