### ISSUE TITLE
 [BUG]节点测速都变成了 N/A, 切换节点也没用

### ISSUE THREAD

**Issue by mkinglife08** [dodois/dosvpn#54]
# Bug Report

**DosVpn 版本:**
 **1.1.3**

**Bug 描述:**
节点测速都变成了 N/A, 切换节点也没用，三种模式的刷新也试过了。

**其他信息:**

![image](https://user-images.githubusercontent.com/7018820/103116743-723a4600-46a2-11eb-878e-5104f0f8f7b4.png)

**Comment by dodois** [comment]
### 请参考以下问题，并自行尝试解决。
1. https://github.com/dodois/dosvpn/issues/49#issuecomment-750005469
2. https://github.com/dodois/dosvpn/issues/53#issue-774493371
3. https://github.com/dodois/dosvpn/issues/52#issue-774236825

> Dodois以多次收到1.1.3版本的类似问题报告，正在分析与解决

**Comment by zyp997** [comment]
@dodois 我用其他软件翻墙时，再打开dosvpn，进行连接时就不会出现测速N/A。
其他时候把别的翻墙软件关了，就会出现测速全部都是N/A。
我反馈一下，希望能有点帮助给你。

**Comment by dodois** [comment]
@zyp997 好的，谢谢反馈

**Comment by allentown521** [comment]
![image](https://user-images.githubusercontent.com/69662387/103136639-118c2700-46fd-11eb-8bb7-1d8e853136a2.png)
测速也是成功的，但是连接不上

**Comment by dodois** [comment]
目前观察到，该问题可能与 设置中心 - 启动后自动连接(开启) 有关。请在新版本到来前暂时关闭该选项，并重启Dosvpn

**Comment by zyp997** [comment]
> 目前观察到，该问题可能与 设置中心 - 启动后自动连接(开启) 有关。请在新版本到来前暂时关闭该选项，并重启Dosvpn

貌似没用啊。。我全都调成手动了，还是不行。

**Comment by Yoka416** [comment]
> 目前观察到，该问题可能与 设置中心 - 启动后自动连接(开启) 有关。请在新版本到来前暂时关闭该选项，并重启Dosvpn

还是没用

**Comment by dodois** [comment]
如果您的1.1.3版本无法正常使用，请回退到 [1.1.2 稳定版](https://github.com/dodois/dosvpn/releases/download/v1.1.2/Dos-VPN-Setup-1.1.2.exe)，感谢您的支持
