### ISSUE TITLE
请问项目还维护吗？

### ISSUE THREAD

**Issue by dhx20150812** [dodois/dosvpn#58]
我刚看见，最近的提交是几个月前的了，不知道作者现在还开发这个项目吗？

**Comment by dodois** [comment]
我们正在开发全新版本的[Doisnet](https://github.com/dodois/Doisnet)，此项目将不再更新但依旧可用，请期待全新的[Doisnet](https://github.com/dodois/Doisnet)上线

**Comment by dhx20150812** [comment]
OK，谢谢您的回复。我会持续关注的！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月9日(周二) 下午2:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dodois/dosvpn] 请问项目还维护吗？ (#58)




 
我们正在开发全新版本的Doisnet，此项目将不再更新但依旧可用，请期待全新的Doisnet上线
