### ISSUE TITLE
智能分流模式会导致部分网站打不开，要切换成全局加速模式才能打开。

### ISSUE THREAD

**Issue by ZK6100HGA** [dodois/dosvpn#6]

**Comment by dodois** [comment]
智能分流，采用  https://github.com/JinnLynn/genpac 的规则，打不开某个网址代表规则中未对该网址进行收录，我们会及时更新规则文件，最大限度保障智能分流模式的可用性。

**Comment by dodois** [comment]
@ZK6100HGA 不好意思，理解有点偏差，我们认为你所说的部分网址，在不开dosvpn的情况下也是打不开的。所以应该不是智能分流本身的问题

**Comment by ZK6100HGA** [comment]
@dodois 我说的部分网站，直连和智能分流都打不开；切换成全局加速模式就能打得开了，据此认为是智能分流的问题，没让该过代理的网站过代理。

**Comment by dodois** [comment]
@ZK6100HGA 好的 了解了
> 智能分流，采用 https://github.com/JinnLynn/genpac 的规则，打不开某个网址代表规则中未对该网址进行收录，我们会及时更新规则文件，最大限度保障智能分流模式的可用性。
