### ISSUE TITLE
请问MAC支持吗？安卓和苹果版在哪里下载？

### ISSUE THREAD

**Issue by yDan** [dodois/dosvpn#7]
MAC版本在哪里下载呢？还有安卓和苹果手机用的有吗？

**Comment by dodois** [comment]
@yDan 由于精力有限，先完善windows版本，MAC版本及安卓、ios将在后续推出，感谢谅解

**Comment by yDan** [comment]
好用，速度不错。请问怎么手动切换节点？

**Comment by dodois** [comment]
将在1.1.0版本推出切换节点功能
> 好用，速度不错。请问怎么手动切换节点？
