### ISSUE TITLE
关于访问一些企业网站遇到AdGuard拦截的问题

### ISSUE THREAD

**Issue by Rqcker** [dodois/dosvpn#8]
访问合法网站遭到AdGuard家长控制
Google 安全浏览显示网站安全
Yandex 安全浏览显示网站安全 
结果AdGuard拒绝用户访问

**Comment by dodois** [comment]
@Rqcker 该情况不在dosvpn的可控范围内，1.1.0版本上线后会提供自由选择节点的能力，届时切换节点可能会对该问题有帮助
